-- Sample Data Script

-- Teams
INSERT ALL
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (1, 'Mercedes', 'Toto Wolff', 'Mercedes')
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (2, 'Red Bull Racing', 'Christian Horner', 'Honda')
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (3, 'Ferrari', 'Mattia Binotto', 'Ferrari')
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (4, 'McLaren', 'Andreas Seidl', 'Mercedes')
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (5, 'Aston Martin', 'Otmar Szafnauer', 'Mercedes')
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (6, 'Alpine', 'Laurent Rossi', 'Renault')
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (7, 'AlphaTauri', 'Franz Tost', 'Honda')
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (8, 'Alfa Romeo Racing', 'Frederic Vasseur', 'Ferrari')
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (9, 'Haas F1 Team', 'Guenther Steiner', 'Ferrari')
INTO Teams (TeamID, TeamName, TeamPrincipalName, EngineSupplier)
VALUES (10, 'Williams', 'Jost Capito', 'Mercedes')
SELECT * FROM dual;

-- Drivers
INSERT ALL
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (44, 'Lewis', 'Hamilton', 1, 'British', TO_DATE('1985-01-07', 'YYYY-MM-DD'))
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (33, 'Max', 'Verstappen', 2, 'Dutch', TO_DATE('1997-09-30', 'YYYY-MM-DD'))
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (5, 'Sebastian', 'Vettel', 3, 'German', TO_DATE('1987-07-03', 'YYYY-MM-DD'))
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (3, 'Daniel', 'Ricciardo', 4, 'Australian', TO_DATE('1989-07-01', 'YYYY-MM-DD'))
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (18, 'Lance', 'Stroll', 5, 'Canadian', TO_DATE('1998-10-29', 'YYYY-MM-DD'))
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (14, 'Fernando', 'Alonso', 6, 'Spanish', TO_DATE('1981-07-29', 'YYYY-MM-DD'))
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (10, 'Pierre', 'Gasly', 7, 'French', TO_DATE('1996-02-07', 'YYYY-MM-DD'))
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (99, 'Antonio', 'Giovinazzi', 8, 'Italian', TO_DATE('1993-12-14', 'YYYY-MM-DD'))
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (9, 'Nikita', 'Mazepin', 9, 'Russian', TO_DATE('1999-03-02', 'YYYY-MM-DD'))
INTO Drivers (DriverID, FirstName, LastName, TeamID, Nationality, DateOfBirth)
VALUES (6, 'Nicholas', 'Latifi', 10, 'Canadian', TO_DATE('1995-06-29', 'YYYY-MM-DD'))
SELECT * FROM dual;

-- Circuits
INSERT ALL
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (1, 'Melbourne Grand Prix Circuit', 'Australia')
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (2, 'Albert Park', 'Australia')
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (3, 'Circuit de Barcelona-Catalunya', 'Spain')
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (4, 'Monza', 'Italy')
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (5, 'Silverstone Circuit', 'United Kingdom')
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (6, 'Hungaroring', 'Hungary')
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (7, 'Spa-Francorchamps', 'Belgium')
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (8, 'Marina Bay Street Circuit', 'Singapore')
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (9, 'Sochi Autodrom', 'Russia')
INTO Circuits (CircuitID, CircuitName, Country)
VALUES (10, 'Yas Marina Circuit', 'United Arab Emirates')
SELECT * FROM dual;

-- Races
INSERT ALL
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (1, 'Australian Grand Prix', 1, TO_DATE('2022-03-20', 'YYYY-MM-DD'))
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (2, 'Spanish Grand Prix', 3, TO_DATE('2022-05-08', 'YYYY-MM-DD'))
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (3, 'Italian Grand Prix', 4, TO_DATE('2022-09-11', 'YYYY-MM-DD'))
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (4, 'British Grand Prix', 5, TO_DATE('2022-07-17', 'YYYY-MM-DD'))
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (5, 'Hungarian Grand Prix', 6, TO_DATE('2022-08-01', 'YYYY-MM-DD'))
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (6, 'Belgian Grand Prix', 7, TO_DATE('2022-08-29', 'YYYY-MM-DD'))
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (7, 'Singapore Grand Prix', 8, TO_DATE('2022-09-25', 'YYYY-MM-DD'))
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (8, 'Russian Grand Prix', 9, TO_DATE('2022-10-02', 'YYYY-MM-DD'))
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (9, 'Abu Dhabi Grand Prix', 10, TO_DATE('2022-11-27', 'YYYY-MM-DD'))
INTO Races (RaceID, RaceName, CircuitID, RaceDate)
VALUES (10, 'United States Grand Prix', 11, TO_DATE('2022-10-24', 'YYYY-MM-DD'))
SELECT * FROM dual;

-- Results
INSERT ALL
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (1, 1, 44, 1, 25)
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (2, 1, 33, 2, 18)
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (3, 2, 44, 1, 25)
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (4, 2, 5, 3, 15)
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (5, 3, 33, 1, 25)
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (6, 3, 44, 2, 18)
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (7, 4, 33, 1, 25)
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (8, 4, 44, 3, 15)
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (9, 5, 33, 1, 25)
INTO Results (ResultID, RaceID, DriverID, DriverPosition, Points)
VALUES (10, 5, 44, 2, 18)
SELECT * FROM dual;

-- DriverOfTheDay
INSERT ALL
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (1, 44)
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (1, 33)
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (2, 5)
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (3, 44)
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (4, 33)
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (5, 44)
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (6, 5)
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (7, 33)
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (8, 44)
INTO DriverOfTheDay (RaceID, DriverID)
VALUES (9, 33)
SELECT * FROM dual;

-- FastestLap
INSERT ALL
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:25:123', 'HH24:MI:SS.FFF'), 1, 44)
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:21:987', 'HH24:MI:SS.FFF'), 2, 44)
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:20:456', 'HH24:MI:SS.FFF'), 3, 33)
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:22:345', 'HH24:MI:SS.FFF'), 4, 33)
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:24:789', 'HH24:MI:SS.FFF'), 5, 44)
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:19:876', 'HH24:MI:SS.FFF'), 6, 44)
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:30:000', 'HH24:MI:SS.FFF'), 7, 33)
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:28:543', 'HH24:MI:SS.FFF'), 8, 33)
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:31:234', 'HH24:MI:SS.FFF'), 9, 44)
INTO FastestLap (LapTime, RaceID, DriverID)
VALUES (TO_TIMESTAMP('01:28:654', 'HH24:MI:SS.FFF'), 10, 44)
SELECT * FROM dual;

-- DNF (Did Not Finish)
INSERT ALL
INTO DNF (RaceID, DriverID, Reason)
VALUES (1, 77, 'Technical Issue')
INTO DNF (RaceID, DriverID, Reason)
VALUES (1, 3, 'Crash')
INTO DNF (RaceID, DriverID, Reason)
VALUES (2, 10, 'Engine Failure')
INTO DNF (RaceID, DriverID, Reason)
VALUES (3, 18, 'Collision')
INTO DNF (RaceID, DriverID, Reason)
VALUES (4, 10, 'Retired')
INTO DNF (RaceID, DriverID, Reason)
VALUES (4, 6, 'Hydraulics')
INTO DNF (RaceID, DriverID, Reason)
VALUES (5, 9, 'Accident')
INTO DNF (RaceID, DriverID, Reason)
VALUES (6, 99, 'Power Unit')
INTO DNF (RaceID, DriverID, Reason)
VALUES (7, 6, 'Transmission')
INTO DNF (RaceID, DriverID, Reason)
VALUES (8, 18, 'Gearbox')
SELECT * FROM dual;

-- Qualifying
INSERT ALL
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (1, 1, TO_TIMESTAMP('01:20:000', 'HH24:MI:SS.FFF'), 1, 44)
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (2, 2, TO_TIMESTAMP('01:20:500', 'HH24:MI:SS.FFF'), 1, 33)
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (3, 3, TO_TIMESTAMP('01:21:000', 'HH24:MI:SS.FFF'), 1, 5)
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (4, 4, TO_TIMESTAMP('01:21:500', 'HH24:MI:SS.FFF'), 2, 44)
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (5, 5, TO_TIMESTAMP('01:22:000', 'HH24:MI:SS.FFF'), 2, 33)
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (6, 6, TO_TIMESTAMP('01:22:500', 'HH24:MI:SS.FFF'), 2, 5)
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (7, 7, TO_TIMESTAMP('01:23:000', 'HH24:MI:SS.FFF'), 3, 44)
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (8, 8, TO_TIMESTAMP('01:23:500', 'HH24:MI:SS.FFF'), 3, 33)
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (9, 9, TO_TIMESTAMP('01:24:000', 'HH24:MI:SS.FFF'), 3, 5)
INTO Qualifying (QualifyingID, QualifyingPosition, LapTime, RaceID, DriverID)
VALUES (10, 10, TO_TIMESTAMP('01:24:500', 'HH24:MI:SS.FFF'), 4, 44)
SELECT * FROM dual;
